### ISSUE TITLE
seems msrc cannot has space in the filename

### ISSUE THREAD

**Issue by huhongbo** [GuoQichen/vue-pswipe#10]
when I have the data like 
src="https://xx.xx.com/has   3space.jpg"
msrc="https://xx.xx.com/has   3space.thumbnail.jpg"

the thumbnail background maybe empty blank or have a random picture, but the 'src' is working fine.

**Comment by GuoQichen** [comment]
Space is not valid ASCII character. Spaces in URIs/URLs should be encoded using %20. Some browsers might auto-correct invalid links in double-quotes with un-encoded spaces in it, but you should not rely on it.

**Comment by huhongbo** [comment]
I already change to the code to replace space, just report it.
