### ISSUE TITLE
PhotoSwipeUI_Default shareEl: false

### ISSUE THREAD

**Issue by imolitor** [GuoQichen/vue-pswipe#11]
Great module!
I want to disable the 'Share' button of the PhotoSwipeUI to false. Can't get my head around on how to do this in vue-pswipe.

**Comment by GuoQichen** [comment]
Thank you!

You can disable it globally,
```js
import VuePswipePlugin from 'vue-pswipe'

Vue.use(VuePswipePlugin, {
    shareEl: false
})
```
Or in every Photoswipe.
```vue
<Photoswipe :options="{ shareEl: false }">
</Photoswipe>
```

**Comment by imolitor** [comment]
Perfect! Thanks for the great mod and the fast reply!!!!
