### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by probil** [GuoQichen/vue-pswipe#13]
According to [bundlephobia](https://bundlephobia.com) the library is quite big in terms of size. 

Let's compare minified size:
```
vue-pswipe: 81.4 kB
photoswipe: 30.9kB
vue       : 63.5kB
```
So currently it's bigger then vue itself which is not good. 
I suppose it to be `~35-40kb`.

I wonder what might cause such a size? 🤔

**Comment by GuoQichen** [comment]
Thank you for your feedback.
In fact, photoswipe's bundle size does not include the default skin. If you count the default skin, photoswipe's bundle size is about 55kB. Then count the size of the vue-class-component and source code, which is about 83kB. 
You can also view the details by running `npm run report`. I will try to reduce the bundle size of the source code.
