### ISSUE TITLE
FR: Custom HTML Content in Slides 

### ISSUE THREAD

**Issue by urbantrout** [GuoQichen/vue-pswipe#15]
It is not possible to add slides with custom HTML as described here: https://photoswipe.com/documentation/custom-html-in-slides.html

**Comment by GuoQichen** [comment]
I will add this feature tomorrow

**Comment by GuoQichen** [comment]
You can use `Vue.prototype.$Pswp.open()` in v0.15.0. See [custom-html](https://github.com/GuoQichen/vue-pswipe/tree/master#custom-html)
