### ISSUE TITLE
this.$Pswp.open does't work

### ISSUE THREAD

**Issue by ricardo17coelho** [GuoQichen/vue-pswipe#17]
this.$Pswp.open doesn't work because this.$Pswp is null.

imported LIB in main.js like you describe on the docs:

`let photoSwipeOptions = {};
import Photoswipe from 'vue-pswipe';
Vue.use(Photoswipe, photoSwipeOptions);`

and want to open photoswipe from js like:
`        handleClick() {
            this.$Pswp.open({
                items: [
                    {
                        html: '<div class="hello-slide"><h1>Hello world <a href="http://example.com">example.com</a></h1></div>',
                    },
                    {
                        src: 'https://farm4.staticflickr.com/3902/14985871946_24f47d4b53_h.jpg',
                    },
                ],
            });
        }`

**Comment by GuoQichen** [comment]
Can you provide a recurring example?
It works in this example.
<a href="https://codesandbox.io/s/funny-shadow-75vxk?fontsize=14&hidenavigation=1&theme=dark">
  <img alt="Edit 75vxk" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

**Comment by ricardo17coelho** [comment]
![image](https://user-images.githubusercontent.com/37732431/77314853-c32da000-6d06-11ea-9250-cac4122de739.png)
I did the same like your example..

**Comment by GuoQichen** [comment]
You need to update to the latest version v0.15.0.  `this.$Pswp.open` was introduced in v0.15.0.

**Comment by ricardo17coelho** [comment]
It works!

i had an old version. v0.14.X
