### ISSUE TITLE
Allow other tags

### ISSUE THREAD

**Issue by ricardo17coelho** [GuoQichen/vue-pswipe#19]
it would be really cool if you could use other tags like for example: vuetify v-img
I can only use tags like img's other div's

**Comment by GuoQichen** [comment]
like this `<v-img v-pswp="'http://placeimg.com/320/320'" src="http://placeimg.com/320/320" />`? I think it works.  `v-pswp` supports custom components.

**Comment by ricardo17coelho** [comment]
Hello Friend,
unfortunately it doesn't work..

`<v-img v-pswp="'http://placeimg.com/320/320'" src="http://placeimg.com/320/320" />`

When I try like this:
```
<Photoswipe>
<v-img v-pswp="'http://placeimg.com/320/320'" src="http://placeimg.com/320/320" />
</Photoswipe>
```
![image](https://user-images.githubusercontent.com/37732431/82863053-72fad600-9f21-11ea-97a6-786c8e7a4031.png)

I can't open the image. the click event does not work but the photoswipe is shown

**Comment by GuoQichen** [comment]
```
```

**Comment by ricardo17coelho** [comment]
Thx! It works!!

**Comment by GuoQichen** [comment]
To prevent Photoswipe from being opened when clicking on a child element, it restricts that only the elements with v-pswp clicked will open Photoswipe, and bubble allows click events to bubble
