### ISSUE TITLE
Can't seem to add event handler to Pswp for Custom HTML implementation

### ISSUE THREAD

**Issue by johnfumaster** [GuoQichen/vue-pswipe#24]
The $Pswp object doesn't expose anything to add event handlers.  

For accessibility reasons, I need to attach a callback to the close event to return the focus to the button that triggered the opening.

**Comment by GuoQichen** [comment]
Fixed in v0.15.1.
```js
this.$Pswp.open({}).listen('close', () => {})
```
Update to v0.15.1, then this code works
