### ISSUE TITLE
not ssr friendly

### ISSUE THREAD

**Issue by chawyehsu** [GuoQichen/vue-pswipe#26]
The photoswipe UI is compiled and is **appended** to `document` object during  the `created()` hook.
https://github.com/GuoQichen/vue-pswipe/blob/08ebf7ad2875e35bef03db463f13e436dadb5908/src/components/photoswipe.vue#L220-L222

https://github.com/GuoQichen/vue-pswipe/blob/08ebf7ad2875e35bef03db463f13e436dadb5908/src/utils.ts#L188-L198

This is not SSR friendly. UI component's compiling and mounting should be split into two operations, and mounting operation should go to the `mounted()` hook.

**Comment by GuoQichen** [comment]
👍  This is a good idea, look like this ? Can you make a PR ? 
```js
    created() {
        UI.mount()
    }
    mounted() {
        UI.append()
        this.gallery = this.$refs.gallery
        if (!this.lazy) this.setImageSize()
        this.openPswp()
    }
```
