### ISSUE TITLE
图片宽高获取问题

### ISSUE THREAD

**Issue by XinChou16** [GuoQichen/vue-pswipe#7]
想问一下，不设置图片的宽高的话，那你是怎么通过`data-pswp-src `来提前获取图片的宽高的

**Comment by GuoQichen** [comment]
通过new Image()的方式，具体可以看代码中的实现[getImageSize](https://github.com/GuoQichen/vue-pswipe/blob/master/src/utils.ts#L30)

**Comment by XinChou16** [comment]
我看到你是用定时器去检查图片是否onload,这会不会有性能消耗问题

**Comment by XinChou16** [comment]
有几万张图片的时候，应该会有缺陷吧

**Comment by GuoQichen** [comment]
其实不会有问题，不用几万张，页面上加载几十张大一点的图片就会感觉页面操作不流畅，这里更大的问题在于渲染这些图片的过程会比较卡。而且new Image对于加载过的图片会直接返回结果
