### ISSUE TITLE
LazyLoading do not work as aspekted

### ISSUE THREAD

**Issue by LrMiLoef** [GuoQichen/vue-pswipe#9]
I noticed with a picture gallery with almost 200 pictures that they are all loaded with the opening of the page. I suppose this is because the original dimensions are determined.  

If you click on a picture from the gallery, it automatically preloads the previous and the following picture. That would be exactly the behavior I would want to have. 

How can you prevent all images from being loaded when initializing the image gallery?

**Comment by GuoQichen** [comment]
Thank you for feedback, I will add this feature recently.

**Comment by GuoQichen** [comment]
You can update to v0.13.1, lazy loading is the default behavior. you can switch by lazy prop.

**Comment by LrMiLoef** [comment]
Thanks for your quick support!
